### ISSUE TITLE
inline-block元素是如何排列的？

### ISSUE THREAD

**Issue by FredWe** [FredWe/IssueBlog#78]
预计将有的参考：w3c标准、IFC、BFC

HTML:

``` HTML
<div class="box">
  <!-- <div id="实验元素1"></div> -->
  <span class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam corporis quae non repellat, recusandae, iusto voluptatum ex odit dolor nihil.</span>
  <!-- <div id="实验元素2"></div> -->
  <!-- <span class="text">Lorem ipsum dolor</span> -->
</div>
```

CSS:

``` CSS
/* 这是一些修饰性样式; */
.box{
  background:pink;
  margin:30px auto;
}
.box:before{
  background:lightblue;
}
/* 这里可以看出height的默认设置是"收缩至合适"的; */
.box{
  height:200px;
}
/* 这里是::before的内容; */
.box:before{
  content: "我是那个备胎元素";
}
/* 这里是影响布局的样式; */
.box{
  width:300px;
}
.text{
  display: inline-block;
}
```

<p data-height="268" data-theme-id="0" data-slug-hash="aOqRZJ" data-default-tab="result" data-user="FredWe" class='codepen'>See the Pen <a href='http://codepen.io/FredWe/pen/aOqRZJ/'>before-breakline-example</a> by Fred.W. (<a href='http://codepen.io/FredWe'>@FredWe</a>) on <a href='http://codepen.io'>CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

为什么这个例子里.text元素会排在::before的下面？

原因是:

::before伪元素 默认为inline元素，.text元素定义为inline-block元素
通过实验 只有“实验元素2”的情况发现， 当剩余宽度（那么这里问题又来了，剩余宽度如何计算？是不是先把word-spacing margin padding先扣除出去？）还能够放得下inline-block时，那么就在右边按照inline的方式放下，否则就在下面另起一行，重新开始放置inline-block

（事实上，这里实际上表现出来的意思是，能够一行放下inline-block里的文本就放在右边，否则就在下面）
